export default {
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "542ca5fc": [() => import(/* webpackChunkName: "542ca5fc" */ "@generated/docusaurus-plugin-content-docs/default/p/physical-ai-course-book-77d.json"), "@generated/docusaurus-plugin-content-docs/default/p/physical-ai-course-book-77d.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/physical-ai-course-book-77d.json")],
  "5e207448": [() => import(/* webpackChunkName: "5e207448" */ "@site/docs/capstone.md"), "@site/docs/capstone.md", require.resolveWeak("@site/docs/capstone.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "7b514018": [() => import(/* webpackChunkName: "7b514018" */ "@site/src/pages/profile.jsx"), "@site/src/pages/profile.jsx", require.resolveWeak("@site/src/pages/profile.jsx")],
  "848cce2f": [() => import(/* webpackChunkName: "848cce2f" */ "@site/docs/module1-ros2.md"), "@site/docs/module1-ros2.md", require.resolveWeak("@site/docs/module1-ros2.md")],
  "985f4c83": [() => import(/* webpackChunkName: "985f4c83" */ "@site/docs/module4-vla.md"), "@site/docs/module4-vla.md", require.resolveWeak("@site/docs/module4-vla.md")],
  "a3713279": [() => import(/* webpackChunkName: "a3713279" */ "@site/docs/deployment.md"), "@site/docs/deployment.md", require.resolveWeak("@site/docs/deployment.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "f2000ee2": [() => import(/* webpackChunkName: "f2000ee2" */ "@site/docs/module3-isaac.md"), "@site/docs/module3-isaac.md", require.resolveWeak("@site/docs/module3-isaac.md")],
  "fcec19fd": [() => import(/* webpackChunkName: "fcec19fd" */ "@site/docs/module2-simulation.md"), "@site/docs/module2-simulation.md", require.resolveWeak("@site/docs/module2-simulation.md")],};
